### ISSUE TITLE
Latest release not logging anything

### ISSUE THREAD

**Issue by bradleyf** [Tostino/jpgAgent#3]
Only startup and shutdown are logged (to the syslog).

Nothing is written to jpgagent.log.

Can't tell if it is running besides using ps or looking at the postgres job status

**Comment by Tostino** [comment]
Fair enough, I didn't change the level anything was being logged at in the last release, just the default log level. What logs would you like to see normally?

**Comment by bradleyf** [comment]
Start/stop of agent. 

Job status start/stop/error

Thanks!

Sent from my iPhone

> On Sep 28, 2018, at 5:59 PM, Adam Brusselback <notifications@github.com> wrote:
> 
> Fair enough, I didn't change the level anything was being logged at in the last release, just the default log level. What logs would you like to see normally?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GoSimpleLLC/jpgAgent","title":"GoSimpleLLC/jpgAgent","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/GoSimpleLLC/jpgAgent"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Tostino in #3: Fair enough, I didn't change the level anything was being logged at in the last release, just the default log level. What logs would you like to see normally?"}],"action":{"name":"View Issue","url":"https://github.com/GoSimpleLLC/jpgAgent/issues/3#issuecomment-425577815"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/GoSimpleLLC/jpgAgent/issues/3#issuecomment-425577815", "url": "https://github.com/GoSimpleLLC/jpgAgent/issues/3#issuecomment-425577815", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [GoSimpleLLC/jpgAgent] Latest release not logging anything (#3)", "sections": [ { "text": "", "activityTitle": "**Adam Brusselback**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@Tostino", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"GoSimpleLLC/jpgAgent\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"GoSimpleLLC/jpgAgent\",\n\"issueId\": 3\n}" }, { "targets": [ { "os": "default", "uri": "https://github.com/GoSimpleLLC/jpgAgent/issues/3#issuecomment-425577815" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 385759328\n}" } ], "themeColor": "26292E" } ]
> -- 
> This message has been scanned for viruses and 
> dangerous content by MailScanner, and is 
> believed to be clean.

-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Comment by Tostino** [comment]
Yeah, that was entirely my mistake. I was busy with my day job when I tried to make that change. The default logging level should have been info, not warn.  I re-did release 1.3.2 because I had made a few mistakes, and included that fix in it.

Sorry for the issues.
https://github.com/GoSimpleLLC/jpgAgent/releases/tag/1.3.2
